database:
  username: <your-database-username> 
  password: <your-database-password> 
  uri: <your-database-uri>
email:
  key: "nenbydebhwkqanpf"
port: "http://localhost:8000/"
jwt:
  jwtKey: "starterproject"
gemini:
  api_key: "AIzaSyCowc1BcSloWsrFoh03sVXqWOIHKV2Hx9E"
  model: "gemini-1.5-flash"
