[build]
  base    = "backend/AASTU-backend-group-6"
  command = "go mod tidy && go run cmd/main.go"
  # Output directory for the build (if you are building a static site, otherwise leave as is)
  publish = "."
[build.environment]
  GO_VERSION = "1.22.5"
  




[functions]
  # Directory where your Netlify Functions are located
  directory = "netlify/functions"