name: product_6
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6
  intl: ^0.19.0
  equatable: ^2.0.5
  dartz: ^0.10.1
  http: ^1.2.2
  mockito: ^5.4.4
  build_runner: ^2.4.11
  internet_connection_checker: ^1.0.0+1
  shared_preferences: ^2.3.1
  flutter_bloc: ^8.1.6
  rxdart: ^0.28.0
  bloc_test: ^9.1.7
  get_it: ^7.7.0
  path: ^1.9.0
  image_picker: ^1.1.2
  http_parser: ^4.0.2
  google_fonts: ^6.2.1
  socket_io_client: ^3.0.0-beta.2
  loading_animations: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - lib/assets/images/
  
