name: starter_project
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.0.1
  equatable: ^2.0.3
  dartz: ^0.10.1
  number_paginator: 0.4.1
  flutter_bloc: ^8.0.1
  get_it: ^7.2.0
  http: ^1.2.2
  rxdart: ^0.28.0
  shared_preferences: ^2.1.1
  internet_connection_checker: ^1.0.0+1
  meta: ^1.12.0
  cupertino_icons: ^1.0.6
  mockito: ^5.0.17
  build_runner: ^2.3.3 



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true
